=== Lichio/beldon/core/src/main/resources/xml/theme.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema
        xmlns="http://belog.beldon.me/schema/theme"
        xmlns:xsd="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://belog.beldon.me/schema/theme"
        elementFormDefault="qualified"
        attributeFormDefault="unqualified">

    <xsd:element name="theme">
        <xsd:annotation>
            <xsd:documentation>插件信息</xsd:documentation>
        </xsd:annotation>
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="name"/>
                <xsd:element ref="author"/>
                <xsd:element ref="email"/>
                <xsd:element ref="url"/>
                <xsd:element ref="logo"/>
                <xsd:element ref="version"/>
                <xsd:choice minOccurs="0">
                    <xsd:element ref="description"/>
                </xsd:choice>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="name" default="未知">
        <xsd:annotation>
            <xsd:documentation>名称</xsd:documentation>
        </xsd:annotation>
        <xsd:simpleType>
            <xsd:restriction base="xsd:string"/>
        </xsd:simpleType>
    </xsd:element>

    <xsd:element name="logo" default="">
        <xsd:annotation>
            <xsd:documentation>名称</xsd:documentation>
        </xsd:annotation>
        <xsd:simpleType>
            <xsd:restriction base="xsd:string"/>
        </xsd:simpleType>
    </xsd:element>

    <xsd:element name="author" default="未知">
        <xsd:annotation>
            <xsd:documentation>作者</xsd:documentation>
        </xsd:annotation>
        <xsd:simpleType>
            <xsd:restriction base="xsd:string"/>
        </xsd:simpleType>
    </xsd:element>

    <xsd:element name="version">
        <xsd:annotation>
            <xsd:documentation>版本</xsd:documentation>
        </xsd:annotation>
        <xsd:simpleType>
            <xsd:restriction base="xsd:string"/>
        </xsd:simpleType>
    </xsd:element>

    <xsd:element name="url">
        <xsd:annotation>
            <xsd:documentation>网址</xsd:documentation>
        </xsd:annotation>
        <xsd:simpleType>
            <xsd:restriction base="xsd:string"/>
        </xsd:simpleType>
    </xsd:element>

    <xsd:element name="email">
        <xsd:annotation>
            <xsd:documentation>邮箱</xsd:documentation>
        </xsd:annotation>
        <xsd:simpleType>
            <xsd:restriction base="xsd:string"/>
        </xsd:simpleType>
    </xsd:element>

    <xsd:element name="description">
        <xsd:annotation>
            <xsd:documentation>描述</xsd:documentation>
        </xsd:annotation>
        <xsd:simpleType>
            <xsd:restriction base="xsd:string"/>
        </xsd:simpleType>
    </xsd:element>

</xsd:schema>

=== Lichio/beldon/web/src/main/webapp/template/theme/beldon/theme.xml
<?xml version="1.0" encoding="UTF-8"?>
<theme xmlns="http://belog.beldon.me/schema/theme"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://belog.beldon.me/schema/theme
        http://belog.beldon.me/schema/plugin/theme.xsd">

    <name>个人模板</name>
    <author>Beldon</author>
    <email>beldon@beldon.me</email>
    <url>http://beldon.me</url>
    <logo>beldon.png</logo>
    <version>1.0</version>
    <description>这是一个模板</description>
</theme>

=== Lichio/beldon/web/src/main/webapp/template/theme/default/theme.xml
<?xml version="1.0" encoding="UTF-8"?>
<theme xmlns="http://belog.beldon.me/schema/theme"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://belog.beldon.me/schema/theme
        http://belog.beldon.me/schema/plugin/theme.xsd">

    <name>默认模板</name>
    <author>Beldon</author>
    <email>beldon@beldon.me</email>
    <url>http://beldon.me</url>
    <logo>logo.png</logo>
    <version>1.0</version>
    <description>这是系统默认的模板</description>
</theme>
